Task.create(title: 'Checar o e-mail', done: false)
Task.create(title: 'Finalizar artigo', done: false)
Task.create(title: 'Estudar Ruby on Rails', done: false)
Task.create(title: 'Estudar React', done: true)
Task.create(title: 'Atualizar o perfil no github', done: true)
